name: CI

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - uses: voidzero-dev/setup-vp@v1.18.0
        with:
          node-version-file: ".node-version"
          cache: true
          run-install: false

      - name: Install Dependencies
        run: vp install

      - name: Generate Worker Types
        run: vp run wrangler:types

      - name: Lint
        run: vp check src/

      - name: Build
        run: vp run build
